language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ccsystem/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ccsystem/docker-react npm run test
#    - docker run ccsystem/docker-react npm run test -- --coverage


deploy:
#    edge: true
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-353645163709"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"